language: go

go:
  - "1.12"

go_import_path: github.com/kubeflow/xgboost-operator

install:
  # get coveralls.io support
  - go get github.com/mattn/goveralls
  # gometalinter is deprecated; migrating to golangci-lint. See https://github.com/alecthomas/gometalinter/issues/590.
  # - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
script:
  - export GO111MODULE=on
  - make
  - go build ./...
  # - golangci-lint run ./...
  # TODO: add goveralls task
