language: go

go:
  - "1.12"

go_import_path: github.com/kubeflow/xgboost-operator

install:
  # get coveralls.io support
  - go get github.com/mattn/goveralls
  # gometalinter is deprecated; migrating to golangci-lint. See https://github.com/alecthomas/gometalinter/issues/590.
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - export GO111MODULE=on
  - go build ./cmd/xgboost-operator.v1alpha1
  - golangci-lint run ./...
  # We customize the build step because by default
  # Travis runs go test -v ./... which will include the vendor
  # directory.
  # With go 1.9 vendor will be automatically excluded.
  # For now though we just run all tests in pkg.
  # And we can not use ** because goveralls uses filepath.Match
  # to match ignore files and it does not support it.
  - goveralls -service=travis-ci -v -package ./... -ignore "client/*/*.go,client/*/*/*.go,client/*/*/*/*.go,client/*/*/*/*/*.go,client/*/*/*/*/*/*.go,client/*/*/*/*/*/*/*.go,testutil/*.go,test_job/*/zz_generated.*.go,test_job/*/*_generated.go,operator/*/zz_generated.*.go,operator/*/*_generated.go,job_controller/test_job_controller.go,job_controller/pod.go,job_controller/job.go,job_controller/status.go"
