apiVersion: xgboostjob.kubeflow.org/v1alpha1
kind: XGBoostJob
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: xgboostjob-sample
spec:
  masterPort: "234567"
  xgbReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: xgboostjob
              image: gcr.io/kubeflow-ci/xgboost-dist-rabit-test:1.0
              ports:
              - containerPort: 9991
                name: xgboostjob-port
    Worker:
      replicas: 3
      restartPolicy: OnFailure
      template:
        spec:
          containers:
            - name: xgboostjob
              image: gcr.io/kubeflow-ci/xgboost-dist-rabit-test:1.0
              ports:
              - containerPort: 9991
                name: xgboostjob-port
